## Klasyfikacja z wykorzystaniem sieci neuronowych

In [3]:
import numpy as np
import keras
from keras.datasets import mnist
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

**Wczytanie i konwersja danych**

In [4]:
training_set, test_set = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [5]:
X_train, y_train = training_set
X_test, y_test = test_set

In [6]:
print(X_train.shape)
(60000, 28, 28)

(60000, 28, 28)


(60000, 28, 28)

In [7]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [8]:
print(X_train.shape)
(60000, 28, 28, 1)

(60000, 28, 28, 1)


(60000, 28, 28, 1)

In [9]:
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

C:\Users\szczy\AppData\Local\Temp\ipykernel_21576\1404525770.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train = X_train.astype(np.float) / 255.0
C:\Users\szczy\AppData\Local\Temp\ipykernel_21576\1404525770.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test = X_test.astype(np.float) / 255.0


**Przygotowanie eksperymentu**

In [10]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [11]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

**Uczenie modelu**

In [14]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 6ms/step - loss: 0.7459 - accuracy: 0.8215 - val_loss: 0.4085 - val_accuracy: 0.8962
Epoch 2/30
375/375 [==============================] - 1s 4ms/step - loss: 0.3895 - accuracy: 0.8962 - val_loss: 0.3352 - val_accuracy: 0.9098
Epoch 3/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3383 - accuracy: 0.9079 - val_loss: 0.3075 - val_accuracy: 0.9140
Epoch 4/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3145 - accuracy: 0.9135 - val_loss: 0.2919 - val_accuracy: 0.9194
Epoch 5/30
375/375 [==============================] - 1s 3ms/step - loss: 0.3007 - accuracy: 0.9165 - val_loss: 0.2851 - val_accuracy: 0.9218
Epoch 6/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2909 - accuracy: 0.9197 - val_loss: 0.2773 - val_accuracy: 0.9240
Epoch 7/30
375/375 [==============================] - 1s 3ms/step - loss: 0.2835 - accuracy: 0.9206 - val_loss: 0.2729 - val_accuracy: 0.9252
Epoch 

**Ocena modelu**

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 2s 7ms/step


In [17]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.97      1135
           2       0.93      0.90      0.92      1032
           3       0.91      0.91      0.91      1010
           4       0.94      0.93      0.93       982
           5       0.92      0.87      0.89       892
           6       0.95      0.95      0.95       958
           7       0.93      0.92      0.93      1028
           8       0.87      0.90      0.89       974
           9       0.90      0.92      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 963    0    1    2    0    6    5    2    1    0]
 [   0 1113    3    3    0    1    3    2   10    0]
 [   5   10  926   16    6    3   12    9   42    3]
 [   3    0   17  921    0   22    2   11   25    9]
 [   1    1    7    1  910   

**Uczenie modeli nieliniowych**

In [18]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_1 (Dense)             (None, 64)                50240     
                                                                 
 dense_2 (Dense)             (None, 128)               8320      
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [21]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 3s 6ms/step - loss: 0.4085 - accuracy: 0.8855 - val_loss: 0.2345 - val_accuracy: 0.9304
Epoch 2/30
375/375 [==============================] - 2s 4ms/step - loss: 0.1961 - accuracy: 0.9425 - val_loss: 0.1700 - val_accuracy: 0.9503
Epoch 3/30
375/375 [==============================] - 2s 4ms/step - loss: 0.1397 - accuracy: 0.9587 - val_loss: 0.1390 - val_accuracy: 0.9600
Epoch 4/30
375/375 [==============================] - 2s 4ms/step - loss: 0.1078 - accuracy: 0.9680 - val_loss: 0.1256 - val_accuracy: 0.9616
Epoch 5/30
375/375 [==============================] - 2s 5ms/step - loss: 0.0861 - accuracy: 0.9743 - val_loss: 0.1097 - val_accuracy: 0.9682
Epoch 6/30
375/375 [==============================] - 2s 5ms/step - loss: 0.0707 - accuracy: 0.9790 - val_loss: 0.1052 - val_accuracy: 0.9686
Epoch 7/30
375/375 [==============================] - 2s 6ms/step - loss: 0.0583 - accuracy: 0.9824 - val_loss: 0.0985 - val_accuracy: 0.9707
Epoch 

In [22]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 1s 4ms/step


In [23]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.97      1032
           3       0.96      0.97      0.97      1010
           4       0.97      0.98      0.98       982
           5       0.99      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.98      0.98      1028
           8       0.97      0.96      0.97       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

[[ 966    0    2    2    1    0    3    3    3    0]
 [   1 1123    3    2    0    1    2    1    2    0]
 [   3    0 1010    4    1    0    4    6    4    0]
 [   2    0   10  982    1    3    0    2    5    5]
 [   0    0    3    1  963   

In [24]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

In [25]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 1600)              0         
                                                                 
 dropout (Dropout)           (None, 1600)             

In [26]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 19s 48ms/step - loss: 0.4034 - accuracy: 0.8751 - val_loss: 0.1084 - val_accuracy: 0.9693
Epoch 2/30
375/375 [==============================] - 22s 59ms/step - loss: 0.1251 - accuracy: 0.9614 - val_loss: 0.0722 - val_accuracy: 0.9802
Epoch 3/30
375/375 [==============================] - 17s 45ms/step - loss: 0.0922 - accuracy: 0.9718 - val_loss: 0.0595 - val_accuracy: 0.9837
Epoch 4/30
375/375 [==============================] - 17s 45ms/step - loss: 0.0782 - accuracy: 0.9757 - val_loss: 0.0493 - val_accuracy: 0.9856
Epoch 5/30
375/375 [==============================] - 28s 75ms/step - loss: 0.0684 - accuracy: 0.9790 - val_loss: 0.0473 - val_accuracy: 0.9862
Epoch 6/30
375/375 [==============================] - 24s 63ms/step - loss: 0.0620 - accuracy: 0.9803 - val_loss: 0.0420 - val_accuracy: 0.9876
Epoch 7/30
375/375 [==============================] - 19s 51ms/step - loss: 0.0557 - accuracy: 0.9822 - val_loss: 0.0426 - val_accuracy:

In [28]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

313/313 [==============================] - 4s 12ms/step


In [29]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       980
           1       1.00      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      1.00      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.98      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 978    0    0    0    0    0    0    1    1    0]
 [   0 1132    2    0    0    0    0    1    0    0]
 [   1    1 1022    0    1    0    0    6    1    0]
 [   0    1    1 1004    0    2    0    1    1    0]
 [   0    0    0    0  979   